### PR TITLE
Clarify isComplexGraph

### PR DESCRIPTION
**Pull request by seth10**

### CODE REVIEW

**Comment by seth10** [comment]
`g` seems to be used in many of these functions, where is it defined?

**Comment by seth10** [comment]
Ah. That's not very clear Jake :P I think it might be more clear if `g` were an argument, no? Also is the new keyword necessary for instantiating a `Set`?

**Comment by ION28** [comment]
`g` is defined as a global variable outside of any function, so it can easily be accessed by any function/event listener on the page. Since it's global, it doesn't need to be passed as an argument anywhere and each function shares the same access to the graph data. Not sure about the requirement of new for a `Set`

**Comment by seth10** [comment]
Oops, I was thinking Python lol. Are my changes valid JavaScript?! I didn't have a quick way to test if the edits in my commit worked

**Comment by seth10** [comment]
Yeah that's pretty cool. I didn't even consciously think about what language I was writing, just intuitively got it by context lol. Interesting. Like "JavaScript" did not pass my mind one while writing that.

I'm all for one-liners, but when that many characters are exactly repeated I think it more clear this way, even if it does add a line.

**Pull request merged**
